# This is copied almost directly from @NobbZ/nixos-config
name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  generate_matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.gen_checks.outputs.checks }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            allow-import-from-derivation = true
          install_url: https://releases.nixos.org/nix/nix-2.28.0/install
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Configure git for SSH
        run: git config --global url."git@gitub.com:".insteadOf "https://github.com/"
      - name: Generate flake.json
        run: |
          nix flake show --json --allow-import-from-derivation > flake.json
      - id: gen_checks
        name: Generate checks
        run: |
          checks=$(jq -c '.checks."x86_64-linux" | keys' < flake.json)
          printf "checks=%s" "$checks" >> $GITHUB_OUTPUT

  build_checks:
    name: Build checks
    runs-on: ubuntu-latest
    needs:
      - generate_matrix
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        check: ${{fromJson(needs.generate_matrix.outputs.checks)}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            allow-import-from-derivation = true
          install_url: https://releases.nixos.org/nix/nix-2.28.0/install
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Configure git for SSH
        run: git config --global url."git@gitub.com:".insteadOf "https://github.com/"
      - name: Build everything
        run: nix build .#checks.x86_64-linux.${{ matrix.check }} --no-link

  check_flake:
    name: Check flake
    runs-on: ubuntu-latest
    needs:
      - generate_matrix
    continue-on-error: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            allow-import-from-derivation = true
          install_url: https://releases.nixos.org/nix/nix-2.28.0/install
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Configure git for SSH
        run: git config --global url."git@gitub.com:".insteadOf "https://github.com/"
      - name: Run checks
        run: |
          nix flake check --keep-going --allow-import-from-derivation
